extend type AccountInstruction {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "AccountInstruction", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `AccountInstruction`.`beneficiary`. It must match the value of `Beneficiary`.`id`. See `@ref` for how to customize it.
  """
  beneficiaryId: UUID @fdc_generated(from: "AccountInstruction.beneficiary", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `AccountInstruction`.`digitalAccount`. It must match the value of `DigitalAccount`.`id`. See `@ref` for how to customize it.
  """
  digitalAccountId: UUID! @fdc_generated(from: "AccountInstruction.digitalAccount", purpose: IMPLICIT_REF_FIELD)
}
extend type Beneficiary {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Beneficiary", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Beneficiary`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Beneficiary.user", purpose: IMPLICIT_REF_FIELD)
}
extend type DigitalAccount {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "DigitalAccount", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `DigitalAccount`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "DigitalAccount.user", purpose: IMPLICIT_REF_FIELD)
}
extend type TrustedAgent {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "TrustedAgent", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `TrustedAgent`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "TrustedAgent.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
