extend type Mutation {
  """
  ✨ Insert a single `AccountInstruction` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  accountInstruction_insert(
    """
    Data object to insert into the table.
    """
    data: AccountInstruction_Data!
  ): AccountInstruction_KeyOutput! @fdc_generated(from: "AccountInstruction", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Beneficiary` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  beneficiary_insert(
    """
    Data object to insert into the table.
    """
    data: Beneficiary_Data!
  ): Beneficiary_KeyOutput! @fdc_generated(from: "Beneficiary", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `DigitalAccount` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  digitalAccount_insert(
    """
    Data object to insert into the table.
    """
    data: DigitalAccount_Data!
  ): DigitalAccount_KeyOutput! @fdc_generated(from: "DigitalAccount", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `TrustedAgent` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  trustedAgent_insert(
    """
    Data object to insert into the table.
    """
    data: TrustedAgent_Data!
  ): TrustedAgent_KeyOutput! @fdc_generated(from: "TrustedAgent", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `AccountInstruction` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  accountInstruction_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [AccountInstruction_Data!]!
  ): [AccountInstruction_KeyOutput!]! @fdc_generated(from: "AccountInstruction", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Beneficiary` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  beneficiary_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Beneficiary_Data!]!
  ): [Beneficiary_KeyOutput!]! @fdc_generated(from: "Beneficiary", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `DigitalAccount` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  digitalAccount_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DigitalAccount_Data!]!
  ): [DigitalAccount_KeyOutput!]! @fdc_generated(from: "DigitalAccount", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `TrustedAgent` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  trustedAgent_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [TrustedAgent_Data!]!
  ): [TrustedAgent_KeyOutput!]! @fdc_generated(from: "TrustedAgent", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `AccountInstruction` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AccountInstruction`.
  """
  accountInstruction_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: AccountInstruction_Data!
  ): AccountInstruction_KeyOutput! @fdc_generated(from: "AccountInstruction", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Beneficiary` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Beneficiary`.
  """
  beneficiary_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Beneficiary_Data!
  ): Beneficiary_KeyOutput! @fdc_generated(from: "Beneficiary", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `DigitalAccount` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DigitalAccount`.
  """
  digitalAccount_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DigitalAccount_Data!
  ): DigitalAccount_KeyOutput! @fdc_generated(from: "DigitalAccount", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `TrustedAgent` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TrustedAgent`.
  """
  trustedAgent_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: TrustedAgent_Data!
  ): TrustedAgent_KeyOutput! @fdc_generated(from: "TrustedAgent", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `AccountInstruction` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AccountInstruction`.
  """
  accountInstruction_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [AccountInstruction_Data!]!
  ): [AccountInstruction_KeyOutput!]! @fdc_generated(from: "AccountInstruction", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Beneficiary` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Beneficiary`.
  """
  beneficiary_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Beneficiary_Data!]!
  ): [Beneficiary_KeyOutput!]! @fdc_generated(from: "Beneficiary", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `DigitalAccount` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DigitalAccount`.
  """
  digitalAccount_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DigitalAccount_Data!]!
  ): [DigitalAccount_KeyOutput!]! @fdc_generated(from: "DigitalAccount", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `TrustedAgent` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TrustedAgent`.
  """
  trustedAgent_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [TrustedAgent_Data!]!
  ): [TrustedAgent_KeyOutput!]! @fdc_generated(from: "TrustedAgent", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `AccountInstruction` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `AccountInstruction` or `null` if not found.
  """
  accountInstruction_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AccountInstruction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AccountInstruction_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: AccountInstruction_Data!
  ): AccountInstruction_KeyOutput @fdc_generated(from: "AccountInstruction", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Beneficiary` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Beneficiary` or `null` if not found.
  """
  beneficiary_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Beneficiary_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Beneficiary_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Beneficiary_Data!
  ): Beneficiary_KeyOutput @fdc_generated(from: "Beneficiary", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `DigitalAccount` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DigitalAccount` or `null` if not found.
  """
  digitalAccount_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DigitalAccount_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DigitalAccount_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DigitalAccount_Data!
  ): DigitalAccount_KeyOutput @fdc_generated(from: "DigitalAccount", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `TrustedAgent` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `TrustedAgent` or `null` if not found.
  """
  trustedAgent_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TrustedAgent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TrustedAgent_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: TrustedAgent_Data!
  ): TrustedAgent_KeyOutput @fdc_generated(from: "TrustedAgent", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `AccountInstruction` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  accountInstruction_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: AccountInstruction_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: AccountInstruction_Data!
  ): Int! @fdc_generated(from: "AccountInstruction", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Beneficiary` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  beneficiary_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Beneficiary_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Beneficiary_Data!
  ): Int! @fdc_generated(from: "Beneficiary", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `DigitalAccount` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  digitalAccount_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DigitalAccount_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DigitalAccount_Data!
  ): Int! @fdc_generated(from: "DigitalAccount", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `TrustedAgent` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  trustedAgent_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: TrustedAgent_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: TrustedAgent_Data!
  ): Int! @fdc_generated(from: "TrustedAgent", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `AccountInstruction` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  accountInstruction_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AccountInstruction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AccountInstruction_FirstRow
  ): AccountInstruction_KeyOutput @fdc_generated(from: "AccountInstruction", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Beneficiary` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  beneficiary_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Beneficiary_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Beneficiary_FirstRow
  ): Beneficiary_KeyOutput @fdc_generated(from: "Beneficiary", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `DigitalAccount` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  digitalAccount_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DigitalAccount_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DigitalAccount_FirstRow
  ): DigitalAccount_KeyOutput @fdc_generated(from: "DigitalAccount", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `TrustedAgent` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  trustedAgent_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TrustedAgent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TrustedAgent_FirstRow
  ): TrustedAgent_KeyOutput @fdc_generated(from: "TrustedAgent", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `AccountInstruction` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  accountInstruction_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: AccountInstruction_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "AccountInstruction", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Beneficiary` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  beneficiary_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Beneficiary_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Beneficiary", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `DigitalAccount` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  digitalAccount_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DigitalAccount_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DigitalAccount", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `TrustedAgent` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  trustedAgent_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: TrustedAgent_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "TrustedAgent", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
