extend type Query {
  """
  ✨ Look up a single `AccountInstruction` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  accountInstruction(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AccountInstruction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AccountInstruction_FirstRow
  ): AccountInstruction @fdc_generated(from: "AccountInstruction", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Beneficiary` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  beneficiary(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Beneficiary_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Beneficiary_FirstRow
  ): Beneficiary @fdc_generated(from: "Beneficiary", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DigitalAccount` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  digitalAccount(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DigitalAccount_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DigitalAccount_FirstRow
  ): DigitalAccount @fdc_generated(from: "DigitalAccount", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TrustedAgent` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  trustedAgent(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TrustedAgent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TrustedAgent_FirstRow
  ): TrustedAgent @fdc_generated(from: "TrustedAgent", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `AccountInstruction` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  accountInstructions(
    """
    Filter condition to narrow down the query results.
    """
    where: AccountInstruction_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AccountInstruction_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AccountInstruction_Having
  ): [AccountInstruction!]! @fdc_generated(from: "AccountInstruction", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Beneficiary` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  beneficiaries(
    """
    Filter condition to narrow down the query results.
    """
    where: Beneficiary_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Beneficiary_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Beneficiary_Having
  ): [Beneficiary!]! @fdc_generated(from: "Beneficiary", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DigitalAccount` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  digitalAccounts(
    """
    Filter condition to narrow down the query results.
    """
    where: DigitalAccount_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DigitalAccount_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DigitalAccount_Having
  ): [DigitalAccount!]! @fdc_generated(from: "DigitalAccount", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TrustedAgent` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  trustedAgents(
    """
    Filter condition to narrow down the query results.
    """
    where: TrustedAgent_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TrustedAgent_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TrustedAgent_Having
  ): [TrustedAgent!]! @fdc_generated(from: "TrustedAgent", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
