extend type AccountInstruction {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "AccountInstruction", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `AccountInstruction` table.
  """
  _count: Int! @fdc_generated(from: "AccountInstruction.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AccountInstruction` table where the `accessGrantDuration` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  accessGrantDuration_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AccountInstruction.accessGrantDuration", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AccountInstruction` table where the `beneficiaryId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  beneficiaryId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AccountInstruction.beneficiaryId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AccountInstruction` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AccountInstruction.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AccountInstruction` table where the `digitalAccountId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  digitalAccountId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AccountInstruction.digitalAccountId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AccountInstruction` table where the `eventTrigger` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  eventTrigger_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AccountInstruction.eventTrigger", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AccountInstruction` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AccountInstruction.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AccountInstruction` table where the `instructionType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  instructionType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AccountInstruction.instructionType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AccountInstruction` table where the `specificInstructions` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  specificInstructions_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AccountInstruction.specificInstructions", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `AccountInstruction` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "AccountInstruction.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `AccountInstruction` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "AccountInstruction.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "AccountInstruction.id", purpose: ENTITY_ID)
}
extend type Beneficiary {
  """
  ✨ List `AccountInstruction` objects in a one-to-many relationship (where `AccountInstruction`.`beneficiary` is this object).
  """
  accountInstructions_on_beneficiary(
    """
    Filter condition to narrow down the query results.
    """
    where: AccountInstruction_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AccountInstruction_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AccountInstruction_Having
  ): [AccountInstruction!]! @fdc_generated(from: "AccountInstruction.beneficiary", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Beneficiary", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Beneficiary` table.
  """
  _count: Int! @fdc_generated(from: "Beneficiary.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beneficiary` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beneficiary.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beneficiary` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beneficiary.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beneficiary` table where the `firstName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  firstName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beneficiary.firstName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beneficiary` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beneficiary.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beneficiary` table where the `lastName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beneficiary.lastName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beneficiary` table where the `phone` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phone_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beneficiary.phone", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beneficiary` table where the `relationship` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  relationship_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beneficiary.relationship", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Beneficiary` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Beneficiary.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Beneficiary` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Beneficiary.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Beneficiary` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Beneficiary.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Beneficiary.id", purpose: ENTITY_ID)
}
extend type DigitalAccount {
  """
  ✨ List `AccountInstruction` objects in a one-to-many relationship (where `AccountInstruction`.`digitalAccount` is this object).
  """
  accountInstructions_on_digitalAccount(
    """
    Filter condition to narrow down the query results.
    """
    where: AccountInstruction_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AccountInstruction_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AccountInstruction_Having
  ): [AccountInstruction!]! @fdc_generated(from: "AccountInstruction.digitalAccount", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "DigitalAccount", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `DigitalAccount` table.
  """
  _count: Int! @fdc_generated(from: "DigitalAccount.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DigitalAccount` table where the `accountType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  accountType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DigitalAccount.accountType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DigitalAccount` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DigitalAccount.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DigitalAccount` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DigitalAccount.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DigitalAccount` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DigitalAccount.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DigitalAccount` table where the `notes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  notes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DigitalAccount.notes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DigitalAccount` table where the `passwordHint` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  passwordHint_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DigitalAccount.passwordHint", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DigitalAccount` table where the `recoveryEmail` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  recoveryEmail_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DigitalAccount.recoveryEmail", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DigitalAccount` table where the `url` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  url_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DigitalAccount.url", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DigitalAccount` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DigitalAccount.userId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DigitalAccount` table where the `username` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  username_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DigitalAccount.username", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `DigitalAccount` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "DigitalAccount.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `DigitalAccount` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "DigitalAccount.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "DigitalAccount.id", purpose: ENTITY_ID)
}
extend type TrustedAgent {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "TrustedAgent", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `TrustedAgent` table.
  """
  _count: Int! @fdc_generated(from: "TrustedAgent.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrustedAgent` table where the `accessLevel` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  accessLevel_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrustedAgent.accessLevel", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrustedAgent` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrustedAgent.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrustedAgent` table where the `designationDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  designationDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrustedAgent.designationDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrustedAgent` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrustedAgent.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrustedAgent` table where the `firstName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  firstName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrustedAgent.firstName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrustedAgent` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrustedAgent.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrustedAgent` table where the `lastName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrustedAgent.lastName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrustedAgent` table where the `phone` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phone_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrustedAgent.phone", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrustedAgent` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrustedAgent.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `TrustedAgent` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "TrustedAgent.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `designationDate` field in the `TrustedAgent` table.
  """
  designationDate_min: Timestamp @fdc_generated(from: "TrustedAgent.designationDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `TrustedAgent` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "TrustedAgent.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `designationDate` field in the `TrustedAgent` table.
  """
  designationDate_max: Timestamp @fdc_generated(from: "TrustedAgent.designationDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "TrustedAgent.id", purpose: ENTITY_ID)
}
extend type User {
  """
  ✨ List `Beneficiary` objects in a one-to-many relationship (where `Beneficiary`.`user` is this object).
  """
  beneficiaries_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Beneficiary_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Beneficiary_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Beneficiary_Having
  ): [Beneficiary!]! @fdc_generated(from: "Beneficiary.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `DigitalAccount` objects in a one-to-many relationship (where `DigitalAccount`.`user` is this object).
  """
  digitalAccounts_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: DigitalAccount_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DigitalAccount_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DigitalAccount_Having
  ): [DigitalAccount!]! @fdc_generated(from: "DigitalAccount.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `TrustedAgent` objects in a one-to-many relationship (where `TrustedAgent`.`user` is this object).
  """
  trustedAgents_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: TrustedAgent_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TrustedAgent_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TrustedAgent_Having
  ): [TrustedAgent!]! @fdc_generated(from: "TrustedAgent.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `emergencyContactEmail` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  emergencyContactEmail_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.emergencyContactEmail", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `emergencyContactName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  emergencyContactName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.emergencyContactName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `emergencyContactPhone` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  emergencyContactPhone_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.emergencyContactPhone", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `photoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  photoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.photoUrl", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: ENTITY_ID)
}
