type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  emergencyContactName: String
  emergencyContactEmail: String
  emergencyContactPhone: String
}

type DigitalAccount @table {
  user: User!
  name: String!
  accountType: String!
  createdAt: Timestamp!
  url: String
  username: String
  passwordHint: String
  recoveryEmail: String
  notes: String
}

type Beneficiary @table {
  user: User!
  firstName: String!
  lastName: String!
  email: String!
  relationship: String!
  createdAt: Timestamp!
  phone: String
}

type AccountInstruction @table {
  digitalAccount: DigitalAccount!
  beneficiary: Beneficiary
  instructionType: String!
  eventTrigger: String!
  createdAt: Timestamp!
  specificInstructions: String
  accessGrantDuration: String
}

type TrustedAgent @table {
  user: User!
  firstName: String!
  lastName: String!
  email: String!
  accessLevel: String!
  createdAt: Timestamp!
  phone: String
  designationDate: Timestamp
}